name: Team approval workflow

on: pull_request_review

jobs:

    LabelWhenApproved:
        runs-on: ubuntu-latest
        steps:
            - name: Label approved pull requests
              uses: abinoda/label-when-approved-action@master
              env:
                APPROVALS: "1"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ADD_LABEL: "approved"
